# Generated by Django 2.2.24 on 2021-06-25 14:04

import datetime
from django.db import migrations, models
import libs.django.db.models
import libs.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', libs.django.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='用户id')),
                ('name', models.CharField(max_length=50, verbose_name='用户名称')),
                ('phone', models.CharField(max_length=50, verbose_name='手机号')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 't_user',
            },
        ),
    ]
