# Generated by Django 2.2.24 on 2021-07-08 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jsonfield_backport.models
import libs.django.db.models
import libs.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', libs.django.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='用户id')),
                ('name', models.CharField(max_length=50, verbose_name='用户名称')),
                ('phone', models.CharField(max_length=50, verbose_name='手机号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='Xxx',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('xxx_id', libs.django.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='xxxid')),
                ('xxx_type', libs.django.db.models.TinyIntField(choices=[(1, '类型1'), (2, '类型2'), (3, '类型3')], default=1, verbose_name='xxx类型')),
                ('xxx_name', models.CharField(default='', max_length=50, verbose_name='xxx名称')),
                ('xxx_name_bin', libs.django.db.models.BinaryCharFiled(default='', max_length=50, verbose_name='xxx名称（区分大小写）')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'xxx表',
                'db_table': 't_xxx',
                'index_together': {('xxx_type', 'xxx_name')},
            },
        ),
        migrations.CreateModel(
            name='Yyy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('yyy_id', libs.django.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='yyyid')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='是否已删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('xxx', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_user.Xxx', to_field='xxx_id', verbose_name='xxxid')),
            ],
            options={
                'verbose_name': 'yyy表',
                'db_table': 't_yyy',
            },
        ),
        migrations.CreateModel(
            name='XxxDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', libs.django.db.models.TextField(null=True, verbose_name='内容')),
                ('long_content', models.TextField(null=True, verbose_name='长内容')),
                ('name_list', django_jsonfield_backport.models.JSONField(null=True, verbose_name='名称列表')),
                ('xxx', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_user.Xxx', to_field='xxx_id', verbose_name='xxxid')),
            ],
            options={
                'verbose_name': 'xxx详情表',
                'db_table': 't_xxx_detail',
            },
        ),
    ]
