# Generated by Django 2.2.24 on 2021-06-24 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import libs.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, verbose_name='店铺名称')),
                ('logo', models.CharField(default='', max_length=255, verbose_name='logo')),
                ('branch_name', models.CharField(default='', max_length=255, verbose_name='分店名称')),
                ('score', models.IntegerField(default=0, verbose_name='评分')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='经度')),
                ('start_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='起送价')),
                ('deliver_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='配送费')),
                ('is_brand', models.BooleanField(default=0, verbose_name='是品牌')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '店铺表',
                'db_table': 't_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopSales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_1', models.DateField(default=libs.datetime.get_date_1th_of_current_month, verbose_name='日期')),
                ('sales', models.IntegerField(default=1, verbose_name='销量')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('shop', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, to='app_mall.Shop', verbose_name='店铺id')),
            ],
            options={
                'verbose_name': '店铺销量表',
                'db_table': 't_shop_sales',
                'unique_together': {('shop', 'date_1')},
            },
        ),
    ]
