# Generated by Django 2.2.24 on 2021-06-25 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import libs.datetime
import libs.django.db.models
import libs.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigShopCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_id', libs.django.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='分类id')),
                ('name', models.CharField(default='', max_length=255, verbose_name='类型名称')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '店铺分类配置表',
                'db_table': 't_config_shop_category',
            },
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_id', libs.django.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='原料id')),
                ('name', models.CharField(max_length=50, verbose_name='原料名称')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品原料表',
                'db_table': 't_item_material',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shop_id', libs.django.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='店铺id')),
                ('name', models.CharField(default='', max_length=255, verbose_name='店铺名称')),
                ('logo', models.CharField(default='', max_length=255, verbose_name='logo')),
                ('branch_name', models.CharField(default='', max_length=255, verbose_name='分店名称')),
                ('score', models.IntegerField(default=0, verbose_name='评分')),
                ('address', models.CharField(max_length=255, verbose_name='店铺地址')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='经度')),
                ('start_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='起送价')),
                ('deliver_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='配送费')),
                ('is_brand', models.BooleanField(default=0, verbose_name='是品牌')),
                ('start_time', models.TimeField(verbose_name='营业起始时间')),
                ('end_time', models.TimeField(verbose_name='营业结束时间')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_mall.ConfigShopCategory', to_field='category_id', verbose_name='店铺分类id')),
            ],
            options={
                'verbose_name': '店铺表',
                'db_table': 't_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shop_comment_id', libs.django.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='店铺评论id')),
                ('is_anonymous', models.BooleanField(default=0, verbose_name='是匿名用户')),
                ('score_service', libs.django.db.models.TinyIntField(default=0, verbose_name='服务分值')),
                ('score_taste', libs.django.db.models.TinyIntField(default=0, verbose_name='口味分值')),
                ('score_pack', libs.django.db.models.TinyIntField(default=0, verbose_name='包装分值')),
                ('score_deliver', libs.django.db.models.TinyIntField(default=0, verbose_name='配送分值')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('shop', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_mall.Shop', to_field='shop_id', verbose_name='店铺id')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_user.User', to_field='user_id', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '店铺评论表',
                'db_table': 't_shop_comment',
            },
        ),
        migrations.CreateModel(
            name='ShopCommentLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('shop_comment', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_mall.ShopComment', to_field='shop_comment_id', verbose_name='店铺评论id')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_user.User', to_field='user_id', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '店铺评论点赞表',
                'db_table': 't_shop_comment_like',
            },
        ),
        migrations.CreateModel(
            name='ShopCommentDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_list', jsonfield.fields.JSONField(null=True, verbose_name='评论图片列表')),
                ('at_item_id_list', jsonfield.fields.JSONField(null=True, verbose_name='at商品id列表')),
                ('content', models.CharField(max_length=2000, null=True, verbose_name='评论内容')),
                ('reply_content', models.CharField(max_length=2000, null=True, verbose_name='商家回复')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('shop_comment', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_mall.ShopComment', to_field='shop_comment_id', unique=True, verbose_name='店铺评论id')),
            ],
            options={
                'verbose_name': '店铺评论详情表',
                'db_table': 't_shop_comment_details',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', libs.django.db.models.FixedCharField(default=libs.uuid.make_uuid, max_length=32, unique=True, verbose_name='商品id')),
                ('logo', models.CharField(default='', max_length=255, verbose_name='商品logo')),
                ('name', models.CharField(default='', max_length=255, verbose_name='商品名称')),
                ('desc', models.CharField(default='', max_length=50, verbose_name='商品简介')),
                ('origin_price', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='原价')),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='现价')),
                ('packing_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='打包费')),
                ('material_id_list', jsonfield.fields.JSONField(null=True, verbose_name='原料id列表')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('shop', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_mall.Shop', verbose_name='店铺id')),
            ],
            options={
                'verbose_name': '商品表',
                'db_table': 't_item',
            },
        ),
        migrations.CreateModel(
            name='ShopSales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_1', models.DateField(default=libs.datetime.get_date_1th_of_current_month, verbose_name='日期')),
                ('sales', models.IntegerField(default=1, verbose_name='销量')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='已删除')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('shop', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_mall.Shop', to_field='shop_id', verbose_name='店铺id')),
            ],
            options={
                'verbose_name': '店铺销量表',
                'db_table': 't_shop_sales',
                'unique_together': {('shop', 'date_1')},
            },
        ),
    ]
