# Generated by Django 2.2.24 on 2021-06-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsales',
            name='shop',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app_mall.Shop', verbose_name='店铺id'),
        ),
    ]
